format = "$directory$git_branch$git_status$python$time$character"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
style = "bold blue"
truncation_length = 3
truncate_to_repo = true

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "
style = "bold purple"

[git_status]
format = "[$all_status$ahead_behind]($style) "
style = "bold green"
conflicted = "⚔️"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
untracked = "?${count}"
stashed = "📦"
modified = "~${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "✘${count}"

[python]
format = "[$symbol($environment)]($style) "
style = "bold yellow"
symbol = ""

[time]
format = "[$time]($style) "
style = "dim bold white"
time_format = "%H:%M"
disabled = false

[cmd_duration]
format = "[$duration]($style) "
style = "bold yellow"
min_time = 5000
show_milliseconds = false
